-- Infrastructure definitions
-- NOTE: Schemas are NOT managed by DCM in this project because they already
-- exist and are owned by a different role. DCM manages objects WITHIN them.
-- If starting fresh, you would DEFINE SCHEMA here and DCM would own them.
