databases:
  DATABASE:
    dev: INTELLIGENCE_DEV_DB
    test: INTELLIGENCE_TEST_DB
    prod: INTELLIGENCE_DB

  SNOWFLAKE_SAMPLE_DATA:
    dev: SNOWFLAKE_SAMPLE_DATA
    test: SNOWFLAKE_SAMPLE_DATA
    prod: SNOWFLAKE_SAMPLE_DATA
